/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as bscTestnetConnections from "./BSC Testnet Connections";
export type { bscTestnetConnections };
export type { CoinFlip } from "./CoinFlip";
export type { TykheLuckyOracle } from "./TykheLuckyOracle";
