/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export * as bscTestnetConnections from "./BSC Testnet Connections";
export { CoinFlip__factory } from "./CoinFlip__factory";
