/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export * as bscTestnetConnections from "./BSC Testnet Connections";
export { CoinFlip__factory } from "./CoinFlip__factory";
export { ITykheLuckyOracle__factory } from "./ITykheLuckyOracle__factory";
export { TykheLuckyOracle__factory } from "./TykheLuckyOracle__factory";
