/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { TykheLuckyOracle } from "./TykheLuckyOracle";
export type { VRFv2Consumer } from "./VRFv2Consumer";
